<?php

declare(strict_types=1);

namespace App\Http\Requests\Api\Wallet;

use App\Actions\GenerateReferenceAction;
use App\Http\Payloads\Wallet\FundWalletPayload;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Str;

class FundWalletRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'amount' => ['required', 'numeric', 'min:1'],
            'email' => ['required', 'email'],
            // Reference can be provided or generated. If provided, validate unique?
            // Usually generated by backend if missing, or validated if present.
            'reference' => ['nullable', 'string', 'unique:transactions,reference'],
        ];
    }

    public function payload(): FundWalletPayload
    {
        return new FundWalletPayload(
            amount: (float) $this->float('amount'),
            email: $this->string('email')->toString(),
            reference: $this->filled('reference') 
                ? $this->string('reference')->toString() 
                : app(GenerateReferenceAction::class)->handle('WAL-FUND'),
        );
    }
}
