openapi: 3.0.3
info:
  title: 'Laravel API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://ship.test'
tags: []
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'Get a bearer token from the `POST /v1/auth/login` endpoint.'
security:
  -
    default: []
paths: []
